function assembleDebugMeta(result, extra = {}) {
  return {
    routeName: result.routeName || extra.routeName || 'unknown',
    pipelineVersion: result.pipelineVersion || 'unknown',
    sourceMode: result.sourceMode || 'longcat',
    provider: result.modelUsed === 'fallback-no-model' ? 'fallback' : (result.sourceMode === 'web_relay' ? 'web_relay' : 'longcat'),
    apiCallAttempted: !!result.apiMeta?.apiCallAttempted,
    apiCallSucceeded: !!result.apiMeta?.apiCallSucceeded,
    preferredModel: result.apiMeta?.preferredModel || '',
    actualModel: result.apiMeta?.actualModel || result.modelUsed || '',
    requestedModel: result.apiMeta?.requestedModel || '',
    providerResolvedModel: result.apiMeta?.providerResolvedModel || '',
    modelPolicy: result.modelPolicy || '',
    modelRoutingStage: result.modelRoutingStage || result.apiMeta?.modelRoutingStage || '',
    modelFallback: !!result.apiMeta?.modelFallback,
    modelFallbackReason: result.apiMeta?.modelFallbackReason || '',
    responseId: result.apiMeta?.responseId || '',
    usage: result.apiMeta?.usage || {},
    usedFallback: !!result.debug?.fallbackUsed || !!result.debug?.roleDraft?.usedFallback || !!result.debug?.renderer?.usedFallback,
    fallbackReason: result.debug?.fallbackReason || result.debug?.roleDraft?.fallbackReason || result.debug?.renderer?.fallbackReason || '',
    roleDraftParseOk: !!result.debug?.roleDraft?.parseOk,
    parseAttemptCount: Number(result.debug?.roleDraft?.parseAttemptCount || 0),
    parseModeTried: result.debug?.roleDraft?.parseModeTried || [],
    finalDraftSource: result.debug?.roleDraft?.finalDraftSource || '',
    outputGuardBlocked: !!result.debug?.outputGuard?.blocked,
    outputGuardBlockedReason: result.debug?.outputGuard?.blockedReason || '',
    selectedTargetPoint: result.turnPlan?.replyTarget?.point || '',
    selectedTargetPointScore: Number(result.turnPlan?.replyTargetScore || 0),
    stateHasCaseFacts: !!(result.stateSnapshot?.caseFacts && (
      result.stateSnapshot.caseFacts.chiefComplaint
      || (result.stateSnapshot.caseFacts.labs || []).length
      || Object.keys(result.stateSnapshot.caseFacts.vitals || {}).length
    )),
    clinicalAnchors: result.turnPlan?.clinicalAnchors || [],
    openLoopsCount: (result.reasoningContext?.openLoops || []).length,
    openLoopsPreview: (result.reasoningContext?.openLoops || []).slice(0, 2),
    agendaStage: result.turnPlan?.agenda || result.reasoningContext?.agenda || '',
    triggerReason: extra.triggerReason || result.triggerReason || 'auto_trigger_unknown',
    metrics: result.metrics || {},
    keyFactCluster: result.contentSkeleton?.currentSnapshotRef?.keyFactCluster || result.reasoningContext?.currentSnapshot?.keyFactCluster || [],
    contradictionAnchor: result.contentSkeleton?.contradictionAnchor || {},
    meetingActionType: result.contentSkeleton?.meetingActionType || '',
    stanceAction: result.contentSkeleton?.stanceAction || '',
    usedTargetPointAsPrimary: !!result.contentSkeleton?.usedTargetPointAsPrimary,
    currentSnapshotPreview: {
      severity: result.reasoningContext?.currentSnapshot?.currentSeverity || '',
      topRisk: result.reasoningContext?.currentSnapshot?.currentTopRisk || '',
      timelineSummary: (result.reasoningContext?.currentSnapshot?.timelineSummary || []).slice(0, 3),
    },
    latestFactTimestampTag: result.reasoningContext?.currentSnapshot?.latestFactTimestampTag || '',
    extractedFactsCount: Number(result.reasoningContext?.caseUnderstanding?.extractedFactsCount || 0),
    suspiciousFactsCount: Number(result.reasoningContext?.caseUnderstanding?.suspiciousFactsCount || 0),
    suspiciousFactsPreview: result.reasoningContext?.caseUnderstanding?.suspiciousFactsPreview || [],
    factTimelineBuilt: !!result.reasoningContext?.caseUnderstanding?.factTimelineBuilt,
    fallbackStage: result.fallbackStage || '',
    technicalFallbackApplied: !!result.technicalFallbackApplied,
    chunkedSendEnabled: !!result.chunkPlan?.chunkedSendEnabled,
    chunkCount: Number(result.chunkPlan?.chunkCount || 0),
    chunkTypes: result.chunkPlan?.chunkTypes || [],
    chunkingReason: result.chunkPlan?.chunkingReason || '',
    interruptedByUser: !!result.interruptedByUser,
    pendingChunksDiscarded: Number(result.pendingChunksDiscarded || 0),
    chunkEmitDurationsMs: result.chunkEmitDurationsMs || [],
    speechAct: result.speechAct || '',
    dialogueMove: result.dialogueMove?.summary || result.dialogueMove?.primary || '',
    mainContradiction: result.mainContradiction || '',
    contradictionType: result.contradictionType || '',
    replanned: !!result.replanned,
    replannedReasonTags: result.replannedReasonTags || [],
    ignoredSuspiciousFacts: result.reasoningContext?.caseUnderstanding?.suspiciousFactsPreview || [],
    finalSkeletonType: result.contentSkeleton?.skeletonType || '',
    relayAttempted: !!result.relayAttempted,
    relaySucceeded: !!result.relaySucceeded,
    relayLatencyMs: Number(result.relayLatencyMs || 0),
    relayAdapterName: result.relayAdapterName || '',
    relayAbortReason: result.relayAbortReason || '',
    providerPolicy: result.providerPolicy || '',
    providerName: result.providerName || (result.sourceMode === 'web_relay' ? 'web_relay_deepseek' : 'longcat'),
    relayPageReused: !!result.relayPageReused,
    relayReadMode: result.relayReadMode || 'final_only',
    relayRequestId: result.relayRequestId || '',
  };
}

module.exports = {
  assembleDebugMeta,
};
